import Head from "next/head";
import Image from "next/image";
import HomePage from "../src/components/HomePage";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import NFTCollectionInfo from "../src/components/NFTCollectionInfo";
export default function Home() {
  
  return (
    <div>
      <Head>
        <title>NFT Factory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <HomePage />
        <NFTCollectionInfo/>
      </main>

    </div>
  );
}
